# Arquivo de Workflow do GitHub Actions para gerar o ranking de gastos
#
# Este workflow roda quinzenalmente para gerar uma lista atualizada
# dos deputados mais gastadores e a salva de volta no repositório.

name: Gerador de Ranking Quinzenal

on:
  schedule:
    # Roda às 05:00 UTC dos dias 1 e 15 de cada mês.
    - cron: '0 5 1,15 * *'
  workflow_dispatch:

jobs:
  generate-ranking:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do repositório
      - name: 1. Baixando o código do projeto
        uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python
      - name: 2. Configurando o ambiente Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar as dependências
      - name: 3. Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Gerar o novo ranking de gastos
      - name: 4. Gerando o ranking de gastos
        run: python3 -m src.gerador_de_ranking

      # Passo 5: Fazer o commit e push do novo ranking para o repositório
      # Esta action verifica se houve mudanças nos arquivos e, se houver,
      # cria um commit e envia para o repositório. Isso mantém o
      # arquivo ranking_gastos.json sempre atualizado.
      - name: 5. Commit do novo ranking
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Atualiza ranking de gastos parlamentares'
          file_pattern: ranking_gastos.json
